apiVersion: v1
kind: Service
metadata:
  name: order-db
spec:
  selector:
    app: order-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 33060
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      name: order-db
      labels:
        app: order-db
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      containers:
        - name: order-db
          image: mysql/mysql-server
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: newpassword
          - name: MYSQL_DATABASE
            value: orders
          - name: MYSQL_USER
            value: user
          - name: MYSQL_PASSWORD
            value: test
          ports:
            - containerPort: 3306
              name: http
