apiVersion: v1
kind: Service
metadata:
  name: static-server-v1
spec:
  selector:
    app: static-server-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server-v1
  template:
    metadata:
      name: static-server-v1
      labels:
        app: static-server-v1
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        "consul.hashicorp.com/connect-service-upstreams": "static-server-v2:2234, order-db:3306"

    spec:
      containers:
        - name: static-server-v1
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
              - name: nginx-index-file1
                mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-index-file1
        configMap:
          name: index-html-configmap1