apiVersion: v1
kind: Service
metadata:
  name: static-server-v1
spec:
  selector:
    app: static-server-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server-v1
  template:
    metadata:
      name: static-server-v1
      labels:
        app: static-server-v1
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        "consul.hashicorp.com/connect-service-upstreams": "static-server-v2:2234, orderdb:3306"

    spec:
      containers:
        - name: static-server-v1
          image: hashicorp/http-echo:latest
          args:
            - -text="hello world-v1"
            - -listen=:8080
          ports:
            - containerPort: 8080
              name: http
