apiVersion: v1
kind: Service
metadata:
  name: static-server-v2
spec:
  selector:
    app: static-server-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server-v2
  template:
    metadata:
      name: static-server-v2
      labels:
        app: static-server-v2
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        "consul.hashicorp.com/connect-service-upstreams": "user-db:3306"
    spec:
      containers:
        - name: static-server-v2
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
              - name: nginx-index-file2
                mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-index-file2
        configMap:
          name: index-html-configmap2