apiVersion: v1
kind: Service
metadata:
  name: static-server-v2
spec:
  selector:
    app: static-server-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-server-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-server-v2
  template:
    metadata:
      name: static-server-v2
      labels:
        app: static-server-v2
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
        - name: static-server-v2
          image: hashicorp/http-echo:latest
          args:
            - -text="hello world-v2"
            - -listen=:8080
          ports:
            - containerPort: 8080
              name: http
